version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 127.0.0.1
    ports:
      - "5431:5432"
  
  united_api:
    build: .
    container_name: united_api
    restart: always
    depends_on:
      -  db
    ports:
      -  "5000:5000"