
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fixtures
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      -  docker_network

  populatedb:
    build: .
    container_name: populate-db
    depends_on:
      - postgres
    command: ["python", "populateDB.py"]
    networks:
      -  docker_network

  manutd_api:
    build: .
    container_name: manutd_api
    depends_on:
      - postgres
    command: ["python", "manutd_api.py"]
    ports:
      - "5000:5000"
    networks:
      -  docker_network

volumes:
  postgres-data:

networks:
  docker_network: