version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fixture
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  populatedb:
    build: .
    container_name: populate-db
    depends_on:
      - postgres
    command: ["python", "populateDB.py"]

  manutd_api:
    build: .
    container_name: flask-api
    depends_on:
      - postgres
    command: ["python", "manutd_api.py"]
    ports:
      - "5000:5000"

volumes:
  postgres-data: