apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "fixtures"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: populatedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: populatedb
  template:
    metadata:
      labels:
        app: populatedb
    spec:
      containers:
        - name: populatedb
          image: your-docker-image:latest
          command: ["python", "populateDB.py"]
      restartPolicy: OnFailure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manutd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manutd-api
  template:
    metadata:
      labels:
        app: manutd-api
    spec:
      containers:
        - name: manutd-api
          image: your-docker-image:latest
          command: ["python", "manutd_api.py"]
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: manutd-api
spec:
  selector:
    app: manutd-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
