apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: manutd-api
  name: manutd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manutd-api
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: manutd-api
    spec:
      containers:
        - args:
            - python
            - manutd_api.py
          image: manutd-api
          name: manutd-api
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
