def NAME = "${params.VM_NAME}"
def SIZE = "${params.VM_SIZE}"
pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: shell
                    image: tamhid/jenkins-agent:latest
                    command:
                    - sleep
                    args:
                    - infinity
            '''
            defaultContainer 'shell'
            retries 2
        }
    }
    stages {
        stage('Main') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'proxmox_api', passwordVariable: 'TF_VAR_proxmox_api_token_secret', usernameVariable: 'TF_VAR_proxmox_api_token_id')]) {
                    withCredentials([usernamePassword(credentialsId: 'vault-token', passwordVariable: 'VAULT_TOKEN', usernameVariable: 'VAULT_ADDR')])  {
                        script{
                            sh "export ANSIBLE_HOST_KEY_CHECKING=False"
                            sh "ansible-playbook '${env.WORKSPACE}'/deployment-pipelines/deploy-vms/main.yml -i '${env.WORKSPACE}'/deployment-pipelines/deploy-vms/inventory/host.ini --extra-vars \"vm_name='${NAME}' vm_size='${SIZE}'\" --tags apply"
                        }
                    }
                }
            }
        }
    }
}
