apiVersion: apps/v1
kind: Deployment
metadata:
  name: united-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: united-app
  template:
    metadata:
      labels:
        app: united-app
    spec:
      containers:
      - name: united-app
        image: tamhid/united
        env:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-token-secret
                key: VAULT_TOKEN
        ports:
        - containerPort: 6000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 6000
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: united-app
spec:
  type: NodePort
  selector:
    app: united-app
  ports:
    - port: 6000
      targetPort: 6000