---
- name: Disable swap (if configured).
  command: swapoff -a

- name: Ensure swap file doesn't exist (if configured).
  file:
    path: /swap.img
    state: absent
  
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-debian
      - curl
      - gnupg
      - containerd.io
    state: present

- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter is loaded
  shell: |
    sudo sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'

- name: Enable IPv4 packet forwarding
  shell: |
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.ipv4.ip_forward = 1
    EOF
    sysctl --system

- name: Configure cGroup Drivers
  shell: |
    containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | sed 's/sandbox_image = "registry.k8s.io\/pause:3.6"/sandbox_image = "registry.k8s.io\/pause3.10"/' | tee /etc/containerd/config.toml

- name: Restart service containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Add Kubernetes repository
  deb822_repository:
    name: kubernetes
    types: deb
    uris: https://pkgs.k8s.io/core:/stable:/v1.32/deb
    suites: /
    signed_by: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
  register: kubernetes_repository

- name: Update Apt cache.
  apt:
    update_cache: true
  when: kubernetes_repository.changed

- name: Install Kubernetes packages.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubeadm
    - kubernetes-cni

- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubectl
    - kubeadm

- name: Ensure kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: true

#containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | sed 's/sandbox_image = "registry.k8s.io\/pause:3.6"/sandbox_image = "registry.k8s.io\/pause3.9"/' |  tee /etc/containerd/config.toml