- hosts: 192.168.117.140
  become: yes
  become_method: sudo
  tasks:
  - name: Login to Vault
    community.hashi_vault.vault_kv2_get:
      url: http://192.168.68.56:8200/
      engine_mount_point: secret
      path: postgres
      auth_method: token
    register: response

  - name: Create postgres namespace and secrets
    copy:
      dest: "../../kubernates/postgres-configmaps.yml"
      content: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: postgres-config
          labels:
            app: postgres
        data:
          POSTGRES_DB: postgres
          POSTGRES_USER: {{ item.key }}
          POSTGRES_PASSWORD: {{ item.value }}
    with_dict: "{{ response.secret }}"
  
  - name: Run kubectl cmds
    shell: |
      microk8s kubectl apply -f ../../kubernates/postgres-configmap.yml
      microk8s kubectl apply -f ../../kubernates/postgres-storage.yml
      microk8s kubectl apply -f ../../kubernates/postgres-deployment.yaml
      microk8s kubectl apply -f ../../kubernates/postgres-service.yaml