- name: Create Certs folder
  file: 
    path: "~/.ssh"
    state: directory

- name: Get cert from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ lookup('env', 'VAULT_ADDR') }}"
    engine_mount_point: secret
    path: id_ecdsa
    auth_method: token
  environment:
    VAULT_TOKEN: "{{ lookup('env', 'VAULT_TOKEN') }}"
  register: response

- name: Create certs
  copy:
    dest: "~/.ssh/id_ecdsa"
    content: "{{ item.value }}"
    mode: '0600'
  with_dict: "{{ response.secret }}"
  no_log: true

- name: Clean up Cert File
  shell: |
    vim --clean ~/.ssh/id_ecdsa -c wq