---
- name: Configure server
  hosts: all
  become: yes
  # roles:
  #   - docker

  tasks:
  # - name: Install Microk8s
  #   community.general.snap:
  #     name: microk8s
  #     classic: true

  - name: Copy over Docker files
    copy:
      src: "{{ item }}"
      dest: /home/tamhid/docker/
    loop:
      - ../docker/docker-compose.yml
      - ../docker/dockerfile

  - name: create and deploy docker compose services
    community.docker.docker_compose_v2:
      project_src: /home/tamhid/docker
      files: /home/tamhid/docker/docker_compose.yml