---
- name: Configure server
  hosts: all
  remote_user: root

  tasks:
  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes
    become_method: sudo
  - name: Install Packages
    apt:
      name: {{ item }}
      state: present
    loop:
      - curl
      - docker
      - microk8s
      - wget
