---
- name: Configure server
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - docker
    
  tasks:
  - name: Install Microk8s
    community.general.snap:
      name: microk8s
      classic: true