---
- name: Configure server
  hosts: all
  become: yes
  # roles:
  #   - docker

  tasks:
  # - name: Install Microk8s
  #   community.general.snap:
  #     name: microk8s
  #     classic: true

  - name: Current working dir
    shell: |
      pwd
    register: output

  - name: Print output
  - debug: msg="{{output.stdout}}"

  - name: create and deploy docker compose services
    community.docker.docker_compose_v2:
      project_src: /var/lib/jenkins/workspace/DevOps Pipeline/docker/.
      files: docker_compose.yml