---
- name: Configure server
  hosts: all
  become: yes
  roles:
    - docker

  tasks:
  - name: Install Microk8s
    community.general.snap:
      name: microk8s
      classic: true

  - name: Current working dir
    shell: |
      pwd

  # - name: create and deploy docker compose services
  #   community.docker.docker_compose_v2:
  #     project_src: 
  #     files: docker_compose.yml