---
- name: Configure server
  hosts: all
  become: yes
  become_method: sudo

  tasks:
  
  - name: Install Docker
    roles:
      - docker

  - name: Install Microk8s
    community.general.snap:
      name: microk8s
      classic: true