---
- name: Deploy Postgres
  hosts: k8master
  become: yes
  gather_facts: no

  tasks:
  - name: Wait for connection
    wait_for_connection:
      delay: 10
      timeout: 300
  - name: Deploy Postgres
    import_role:
      name: roles/k8-postgres